### ISSUE TITLE
YARD-Coverage being reported inconsistently

### ISSUE THREAD

**Issue by nimylian** [dkubb/yardstick#51]
I have encountered an issue with the `Yardstick::Rake::Verify`. When I run my rake task, the output is as follows:
```
$ bundle exec rake yard:verify
YARD-Coverage: 82.3% (threshold: 100%)
rake aborted!
YARD-Coverage must be at least 100% but was 81.7%
```
After the first time `#total_coverage` is called, in`Yardstick::Rake::Verify#verify_measurements` LOC:54, the `measurements.coverage` is a much larger set than in subsequent calls. 

I've added some debugger to demonstrate:
```
$ bundle exec rake yard:verify
measurements.coverage: 13749/16690
YARD-Coverage: 82.3% (threshold: 100%)
measurements.coverage: 193/236
measurements.coverage: 193/236
YARD-Coverage must be at least 100% but was 81.7%
```

## config/yardstick.yml:
```yaml
---
threshold: 100
path: 'app/**/*.rb'
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: false
    exclude: []
  ApiTag::Inclusion:
    enabled: false
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: false
    exclude: []
  ApiTag::PrivateMethod:
    enabled: false
    exclude: []
  ExampleTag:
    enabled: false
    exclude: []
  ReturnTag:
    enabled: true
    exclude: []
  Summary::Presence:
    enabled: true
    exclude: []
  Summary::Length:
    enabled: false
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: false
    exclude: []
```
## Rakefile
```
if Rails.env.development?
  require 'yardstick/rake/verify'
  require 'yardstick/rake/measurement'

  namespace :yard do
    options = YAML.load_file('config/yardstick.yml')

    Yardstick::Rake::Measurement.new(:measure, options) do |measurement|
      measurement.output = 'doc/•yardstick_report.txt'
    end

    Yardstick::Rake::Verify.new(:verify, options)

    task :save_stats => :environment do
      sh %{yard stats --list-undoc --compact > 'doc/•undocumented.txt'}
    end
  end
end
```
