### ISSUE TITLE
Customizable rules

### ISSUE THREAD

**Issue by indrekj** [dkubb/yardstick#8]
Hi,

I find yardstick very useful. But I'm not really a fan of the "@api" tag validation. What is your take on the customizable rules like the reek gem has? I'm okay with implementing this if it is a good idea. I'm thinking something like this:

``` yaml

---
ApiTag:
  enabled: true
```
